version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/Team-A-P2-API.war Team-A-P2-API.war
artifacts:
  files:
    - Team-A-P2-API.war
    - .ebextensions/**/*
  base-directory: 'target/Team-A-P2-API'