version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  post_build:
    commands:
      - mvn package
      - mv target/p2-1.0-SNAPSHOT.war p2-1.0-SNAPSHOT.war
artifacts:
  files:
    - p2-1.0-SNAPSHOT.war
    - .ebextensions/**/*
#  base-directory: 'target/Team-A-P2-API'